from typing import List, Dict, Any

LITERATURE_PAPERS: List[Dict[str, Any]] = [
    {
        "id": 1,
        "author_year": "Zhou et al. (2024)",
        "title": "An LLM-driven Approach to Gain Cybercrime Insights with Evidence Networks / USENIX (Conference Poster)",
        "summary": "Shows how to use LLMs to scan raw mobile data and auto-build evidence networks called Forensic Intelligence Graphs (FIGs).",
        "focus": "Speeding up mobile data analysis to fix the manual bottleneck when investigators review chat logs and phone records.",
        "methodology": "Dumps raw logs into plain text, uses GPT-4 to extract key entities like names and numbers, and links them into a relational graph.",
        "findings": "The pipeline hit over 91% accuracy in finding evidence entities and 93% accuracy in mapping their connections compared to baseline tools.",
        "limitations": "LLMs are still probabilistic and can hallucinate details, which is a major problem since court evidence requires 100% deterministic validation.",
        "remarks": "Reviewed by Karthik - By Google Search",
        "narrative": "Zhou et al. (2024) built a setup that uses LLMs to extract evidence from mobile data and map it into Forensic Intelligence Graphs. It proves we can automate the time-consuming process of manual log reviews with high accuracy, but it also highlights a major gap: LLM hallucinations are a liability in legal contexts, meaning we need strict deterministic validation steps."
    },
    {
        "id": 2,
        "author_year": "Chernyshev et al. (2025)",
        "title": "Large language models in digital forensics: capabilities, challenges and future directions / ScienceDirect",
        "summary": "A deep survey mapping out where LLMs actually help in the standard digital forensics workflow (DFRWS) and where they fail.",
        "focus": "Balancing the massive data-processing speed of GenAI with the strict legal rules of evidence tracking and reproducibility.",
        "methodology": "Evaluated 33 recent peer-reviewed papers that used LLMs for analyzing crime scenes, linking artifacts, and writing reports.",
        "findings": "LLMs are great for summarizing huge datasets and spotting patterns, but they completely fail at explainability because they don't produce identical outputs every time.",
        "limitations": "There is no standard framework right now to safely integrate non-deterministic AI outputs into legally admissible workflows.",
        "remarks": "Reviewed by Karthik - Assisted using Perplexity",
        "narrative": "Chernyshev et al. (2025) reviewed how LLMs perform across different stages of forensic investigations. They found that while LLMs are excellent at pattern matching across huge, messy datasets, their lack of explainability and non-deterministic nature creates a massive conflict with the strict, predictable standards required for court evidence."
    },
    {
        "id": 3,
        "author_year": "Khatiwala, Addai & Xu (2025)",
        "title": "Evaluating the Reliability of Digital Forensic Evidence Discovered by Large Language Model: A Case Study / IEEE COMPSAC 2025",
        "summary": "Introduces a system that combines a Digital Forensic Knowledge Graph (DFKG) with an LLM to extract artifacts and double-check the results.",
        "focus": "Making sure AI-extracted evidence is completely trustworthy and trackable to avoid false classification errors.",
        "methodology": "Uses an LLM to refine data parsed from system artifacts, logs every entry with a unique identifier (UID), and matches them across sources.",
        "findings": "The system achieved over 95% accuracy in grabbing artifacts while keeping the digital chain of custody completely intact.",
        "limitations": "It takes a lot of computing power to run, and the system struggles when dealing with encrypted or highly obfuscated data from custom apps.",
        "remarks": "Reviewed by Karthik - Assisted using Perplexity",
        "narrative": "Khatiwala, Addai & Xu (2025) focused on making AI evidence reliable by building a Digital Forensic Knowledge Graph. By assigning strict unique IDs (UIDs) to every log entry, they hit 95% accuracy in artifact extraction while keeping the chain of custody secure. However, it requires heavy hardware resources and still hits a wall when encountering encrypted application data."
    },
    {
        "id": 4,
        "author_year": "Xu et al. (2024)",
        "title": "Leveraging Large Language Models for Cyber Threat Intelligence / IEEE Transactions on Information Forensics and Security",
        "summary": "Examines how LLMs can automate the extraction and classification of cyber threat indicators from unstructured threat reports and dark web forums.",
        "focus": "Automating CTI (Cyber Threat Intelligence) collection to replace slow, manual analyst workflows when processing high-volume threat data.",
        "methodology": "Fed raw threat reports and forum posts into a fine-tuned LLM pipeline to extract IOCs (Indicators of Compromise) and classify threat actor behavior.",
        "findings": "Achieved 89% precision in IOC extraction and reduced analyst processing time by nearly 60% compared to traditional rule-based NLP tools.",
        "limitations": "The model performs poorly on non-English dark web content and struggles with domain-specific jargon from newer threat actor communities.",
        "remarks": "Reviewed by Aryan - Assisted using Claude",
        "narrative": "Xu et al. (2024) demonstrated that fine-tuned LLMs can dramatically accelerate threat intelligence gathering by automating IOC extraction from messy, unstructured sources. While the precision gains are significant, the model's weakness with non-English content and evolving slang reveals a critical gap in coverage for global threat landscapes."
    },
    {
        "id": 5,
        "author_year": "Arash et al. (2024)",
        "title": "AI-Assisted Log Analysis for Intrusion Detection: An LLM-Based Framework / Computers & Security (Elsevier)",
        "summary": "Proposes an LLM-based framework that reads raw system and network logs to detect intrusion patterns without relying on predefined signature rules.",
        "focus": "Moving intrusion detection beyond rigid signature databases toward flexible, context-aware log interpretation using generative AI.",
        "methodology": "Used a prompt-engineering approach to feed chunked syslog and network traffic data into GPT-4, generating natural language summaries of anomalous behavior.",
        "findings": "The framework correctly flagged 87% of intrusion events in benchmark datasets and outperformed traditional SIEM tools on zero-day attack patterns.",
        "limitations": "High false-positive rates were observed on noisy enterprise logs, and the system cannot process real-time streams due to API latency constraints.",
        "remarks": "Reviewed by Aryan - By Google Search",
        "narrative": "Arash et al. (2024) showed that LLMs can replace rigid, signature-based intrusion detection by reading raw logs contextually. Their framework outperformed traditional SIEM systems especially against zero-day threats, but the high false-positive rate on noisy logs and real-time processing bottleneck remain serious barriers before operational deployment."
    },
    {
        "id": 6,
        "author_year": "Motlagh et al. (2024)",
        "title": "Large Language Models in Cybersecurity: State-of-the-Art / arXiv Preprint",
        "summary": "A comprehensive survey covering how LLMs are currently being applied across offensive and defensive cybersecurity tasks including malware analysis, phishing detection, and vulnerability discovery.",
        "focus": "Mapping the full landscape of LLM use in cybersecurity to identify where the technology is mature and where critical gaps remain.",
        "methodology": "Systematically reviewed over 50 papers published between 2022-2024, categorizing them by cybersecurity task type and evaluating reported performance metrics.",
        "findings": "LLMs show strong performance in code vulnerability detection and phishing classification, but remain unreliable for binary malware analysis and adversarial robustness.",
        "limitations": "Most studies use controlled lab datasets that don't reflect real-world adversarial conditions, leading to overly optimistic accuracy numbers.",
        "remarks": "Reviewed by Aryan - Assisted using Claude",
        "narrative": "Motlagh et al. (2024) provided one of the most thorough mappings of LLM applications in cybersecurity to date. Their survey confirms that while LLMs excel at text-heavy tasks like phishing detection and code review, the field still lacks evaluation on real-world adversarial data, meaning reported benchmarks are likely inflated compared to what practitioners would encounter in live environments."
    },
    {
        "id": 7,
        "author_year": "Sharma et al. (2025)",
        "title": "ForensicLLM: A Local Large Language Model for Digital Forensics / ScienceDirect",
        "summary": "Developed ForensicLLM, a local domain-specific LLM for digital forensics by fine-tuning LLaMA-3.1-8B on forensic research papers and artifact data.",
        "focus": "The model improves forensic knowledge retrieval while preserving data privacy in secure environments.",
        "methodology": "Fine-tuned LLaMA-3.1-8B using digital forensic papers and artifact data through a Retrieval Augmented Fine-Tuning (RAFT) approach, then evaluated its performance against baseline and RAG models.",
        "findings": "ForensicLLM outperformed the base and RAG models, achieving 86.6% citation accuracy and better forensic response quality.",
        "limitations": "The model relies on GPT-4-generated training data and artifact metadata, which may introduce bias. It also occasionally produces incorrect citations.",
        "remarks": "Reviewed by Shreya - Assisted using ChatGPT",
        "narrative": "Sharma et al. (2025) proposed ForensicLLM, a specialized local large language model for digital forensic investigations. The model was built on a 4-bit quantized LLaMA-3.1-8B and fine-tuned using digital forensic research papers and forensic artifacts through a Retrieval Augmented Fine-Tuning (RAFT) approach. Results showed that ForensicLLM outperformed both the baseline LLaMA and RAG models, achieving 86.6% source attribution accuracy. However, the study relied on GPT-4-generated training data, highlighting the need for richer forensic datasets."
    },
    {
        "id": 8,
        "author_year": "Chernyshev et al. (2026)",
        "title": "Large language models in digital forensics: Capabilities, Challenges and Future directions / ScienceDirect",
        "summary": "Reviews the application of LLMs across digital forensic workflows and identifies key challenges, opportunities, and research trends.",
        "focus": "Use of LLMs and generative AI in digital forensic investigations.",
        "methodology": "Systematic literature review using PRISMA guidelines, analyzing 33 studies published between 2023-2025.",
        "findings": "LLMs can support evidence analysis, threat hunting, query generation, and forensic investigations, but several technical and forensic challenges remain.",
        "limitations": "Limited empirical validation, lack of standardized benchmarks, and concerns regarding forensic integrity, privacy, and reliability.",
        "remarks": "Reviewed by Shreya - Assisted using ChatGPT",
        "narrative": "Chernyshev et al. (2026) conducted a systematic literature review to examine the role of large language models in digital forensics. Using the PRISMA methodology, the authors analyzed 33 studies published between 2023 and 2025. The review found that LLMs can assist in several forensic tasks, including evidence analysis, threat hunting, query generation, and forensic investigations. However, challenges related to reliability, forensic integrity, privacy, and the lack of standardized evaluation benchmarks continue to limit widespread adoption."
    },
    {
        "id": 9,
        "author_year": "Loumachi, Ghanem & Ferrag (2024–2025)",
        "title": "GenDFIR: Advancing Cyber Incident Timeline Analysis Through Retrieval-Augmented Generation and Large Language Models / arXiv Preprint",
        "summary": "Proposes GenDFIR, an AI-powered framework that automates cyber incident timeline analysis using RAG and Llama 3.1 8B, achieving high accuracy in DFIR investigations.",
        "focus": "Automating DFIR timeline analysis (artefact analysis, event correlation, anomaly detection) by integrating Generative AI with RAG into a local framework.",
        "methodology": "The framework preprocesses incident events into a structured knowledge base and uses a RAG-based Llama 3.1 8B agent to retrieve relevant evidence and generate timeline reports.",
        "findings": "GenDFIR achieved 97.51% overall performance and effectively performed evidence retrieval, event correlation, root cause analysis, and timeline report generation across tested scenarios.",
        "limitations": "The framework was evaluated only on synthetic datasets and may face token limitations, occasional hallucinations, and lacks support for anti-forensics scenarios.",
        "remarks": "Reviewed by Shreya - Assisted using Claude Sonnet 4.6",
        "narrative": "Loumachi, Ghanem, and Ferrag (2024) proposed GenDFIR, a RAG-powered framework for automating cyber incident timeline analysis. The framework combines semantic retrieval with Llama 3.1 8B to correlate events, identify anomalies, and generate human-readable timeline reports. Evaluation on synthetic scenarios achieved a performance score of 97.51%. However, the study was limited to synthetic datasets and faced challenges such as occasional hallucinations, token constraints, and the lack of domain-specific fine-tuning."
    },
    {
        "id": 10,
        "author_year": "Wickramasekara, Breitinger & Scanlon (2025)",
        "title": "Exploring the Potential of Large Language Models for Improving Digital Forensic Investigation Efficiency / FSI: Digital Investigation",
        "summary": "A comprehensive review and experimental study examining how LLMs can improve efficiency across the full digital forensic investigation pipeline.",
        "focus": "LLM utility across timeline reconstruction, log anomaly detection, incident narration, automated script generation, and keyword list creation.",
        "methodology": "Systematic literature review supplemented with experimental evaluation using ChatGPT. AutoDFBench framework introduced, utilizing NIST CFTT benchmarks.",
        "findings": "LLMs demonstrated strong performance in timeline reconstruction from event logs, anomaly detection in drone flight data via sentiment analysis, and automated code generation.",
        "limitations": "Evaluation limited to specific LLM models; comparative multi-model benchmarking is absent. No end-to-end framework integrating multiple LLM capabilities.",
        "remarks": "Reviewed by Kritika - Assisted using Claude Sonnet 4.6",
        "narrative": "Wickramasekara, Breitinger, and Scanlon (2025) explored LLM utility across the entire forensic lifecycle. Introducing the AutoDFBench benchmarking framework aligned with NIST's Computer Forensics Tool Testing Program, they found LLMs highly effective in timeline reconstruction, log-based anomaly detection, and automated script generation. Key limitations include the probabilistic nature of LLM output, the absence of multi-model comparative analysis, and the lack of end-to-end operational frameworks."
    },
    {
        "id": 11,
        "author_year": "Xu, Zhang & Xu (2024)",
        "title": "Transforming Digital Forensics with Large Language Models: Unlocking Automation, Insights, and Justice / Proceedings of ACM CIKM 2024",
        "summary": "Explores the transformative potential of LLMs across the full digital forensics and justice pipeline -- from automated evidence triage to generating legally defensible reports.",
        "focus": "Holistic exploration of LLM applications in digital forensics with emphasis on automation of evidence analysis and justice system implications.",
        "methodology": "Tutorial-style synthesis combining literature review with hands-on demonstration of LLM capabilities (prompt engineering, RAG-based evidence retrieval, multi-modal analysis).",
        "findings": "LLMs can substantially automate repetitive forensic tasks (evidence triage, keyword generation, report drafting). RAG-based approaches improve factual grounding for forensic queries.",
        "limitations": "Primarily conceptual and tutorial-oriented; limited empirical validation. Legal and ethical dimensions of LLM-generated forensic evidence not resolved.",
        "remarks": "Reviewed by Kritika - Assisted using Claude Sonnet 4.6",
        "narrative": "Xu, Zhang, and Xu (2024) presented a comprehensive tutorial at ACM CIKM 2024, demonstrating RAG-based architectures for grounding LLM outputs in forensic knowledge bases. The authors argue that LLMs can reduce forensic investigation backlogs and democratize access to expertise. However, limitations include a primarily conceptual orientation and unresolved questions around the legal admissibility of LLM-assisted findings."
    },
    {
        "id": 12,
        "author_year": "Michelet et al. (2025)",
        "title": "Fine-Tuning Large Language Models for Digital Forensics: Case Study and General Recommendations / ACM Digital Threats",
        "summary": "Investigates the process of fine-tuning general-purpose LLMs for digital forensics applications, specifically forensic report writing and chat summarization.",
        "focus": "Fine-tuning methodology and best practices for adapting LLMs to digital forensics tasks.",
        "methodology": "Fine-tuning experiments using ChatGPT-3.5 and LLaMA-2-13B on forensic report datasets, comparing report quality, completeness, and accuracy.",
        "findings": "Fine-tuned LLMs produce more accurate and domain-relevant forensic outputs compared to base models. ChatGPT-3.5 outperformed LLaMA-2-13B in report quality.",
        "limitations": "Both models required significant human proofreading; full automation remains premature. Datasets were limited in size and diversity.",
        "remarks": "Reviewed by Kritika - Assisted using Claude Sonnet 4.6",
        "narrative": "Michelet et al. (2025) provided a systematic investigation into fine-tuning LLMs for digital forensics. Their study compared fine-tuned ChatGPT-3.5 and LLaMA-2-13B, finding that while fine-tuning improved domain relevance and accuracy, both models required significant human proofreading before outputs could be considered forensically reliable. The authors conclude that fine-tuning does not eliminate hallucination risks."
    },
    {
        "id": 13,
        "author_year": "Scanlon et al. (2023)",
        "title": "ChatGPT for Digital Forensic Investigation: The Good, The Bad, and The Unknown / FSI: Digital Investigation",
        "summary": "This paper assesses the impact and potential of ChatGPT (GPT-3.5 and GPT-4) on the field of digital forensics, systematically identifying where the model helps and falls short.",
        "focus": "Application of general-purpose LLMs to real-world digital forensics tasks, with a focus on potential benefits and inherent risks in court-admissible contexts.",
        "methodology": "Experimental evaluation testing ChatGPT across network packet analysis (Heartbleed vulnerability), Sysmon log files, keyword searching, and regex/script generation.",
        "findings": "ChatGPT showed strength in summarizing documents, generating regex patterns, and aiding coding tasks, but demonstrated unreliable outputs in entity recognition and hallucination-prone responses.",
        "limitations": "Dependence on cloud-based APIs raises serious data confidentiality issues. The tool cannot directly ingest live forensic evidence or operate in air-gapped environments.",
        "remarks": "Reviewed by Jagrat - By using Google search",
        "narrative": "Scanlon et al. (2023) conducted one of the first systematic empirical evaluations of ChatGPT in digital forensics. Their experiments covered artifact parsing, Sysmon log analysis, and script generation. While identifying low-risk applications like document summarization, they highlighted critical limitations, including data privacy concerns with cloud APIs, training biases, and the necessity of an experienced investigator to validate all outputs."
    },
    {
        "id": 14,
        "author_year": "Loumachi et al. (2025)",
        "title": "Advancing Cyber Incident Timeline Analysis Through Retrieval-Augmented Generation and Large Language Models / MDPI Computers",
        "summary": "This paper introduces GenDFIR, a context-specific framework powered via LLM capabilities for automating cyber incident timeline analysis.",
        "focus": "Automating forensic timeline analysis of DFIR by integrating a zero-shot Llama 3.1 8B model with a RAG agent to correlate large volumes of logs.",
        "methodology": "Two-stage framework: (1) data preprocessing into a structured knowledge base document, and (2) context retrieval using a RAG agent based on user prompts.",
        "findings": "The GenDFIR framework effectively correlated events across heterogeneous forensic data sources, reconstructed chronological attack sequences, and reduced manual investigator effort.",
        "limitations": "Tested only on synthetic datasets in a controlled laboratory environment. Performance with other models (Gemini, Claude) and chain-of-custody compliance remain open problems.",
        "remarks": "Reviewed by Jagrat - Assisted using Claude Sonnet 4.6",
        "narrative": "Loumachi et al. (2025) proposed GenDFIR, a RAG-augmented LLM framework specifically designed to automate cyber incident timeline analysis. By structuring incident events into a vector knowledge base and deploying Llama 3.1 8B, the system semantically retrieves and enriches relevant events. While the system demonstrated practical capability in correlating evidence, validation on real-world multi-device datasets remains an open challenge."
    },
    {
        "id": 15,
        "author_year": "Oh et al. (2024)",
        "title": "volGPT: Evaluation on Triaging Ransomware Process in Memory Forensics with Large Language Model / FSI: Digital Investigation (DFRWS)",
        "summary": "Proposes a novel ransomware triage method leveraging a Large Language Model (volGPT) in conjunction with the Volatility memory forensics framework.",
        "focus": "Memory forensics automation to triage Windows memory dumps containing obfuscated or masqueraded ransomware processes.",
        "methodology": "The volGPT plugin extracts process info from Volatility's pslist, vadinfo, and malfind, formatting it into a decision rule-based prompt for GPT-3.5-turbo.",
        "findings": "volGPT achieved 94% accuracy in detecting processes suspected of ransomware behavior and reduced the count of suspicious processes requiring manual check by 10%.",
        "limitations": "The framework relies exclusively on GPT-3.5-turbo (pre-2022 corpus limit), outputs are stochastic (non-deterministic), and token limits forced truncation of critical binary outputs.",
        "remarks": "Reviewed by Jagrat - By using Google search",
        "narrative": "Oh et al. (2024) introduced volGPT, a novel memory forensics triage framework that integrates GPT-3.5-turbo with the Volatility framework to automate ransomware process identification. Evaluated on 500 memory dumps across five ransomware families, volGPT achieved 94% detection accuracy. However, key limitations include pre-2022 training cutoff, non-deterministic responses, and token limits that truncate tool logs, highlighting that further work is needed before legal deployment."
    }
]
